const prepositions = [
    { english: 'about', turkish: 'hakkında', definition: 'on the subject of' },
    { english: 'above', turkish: 'üstünde', definition: 'at a higher level or layer than' },
    { english: 'across', turkish: 'karşısında', definition: 'from one side to the other' },
    { english: 'after', turkish: 'sonra', definition: 'following in time' },
    { english: 'against', turkish: 'karşı', definition: 'in opposition to' },
    { english: 'along', turkish: 'boyunca', definition: 'moving in a constant direction on' },
    { english: 'among', turkish: 'arasinda', definition: 'in the midst of' },
    { english: 'around', turkish: 'etrafında', definition: 'in a circle or near' },
    { english: 'at', turkish: 'de', definition: 'used to indicate a point in space or time' },
    { english: 'before', turkish: 'önce', definition: 'during the period of time preceding' },
    { english: 'behind', turkish: 'arkasında', definition: 'at the back of' },
    { english: 'below', turkish: 'aşağısında', definition: 'lower than' },
    { english: 'beneath', turkish: 'altında', definition: 'in a lower position' },
    { english: 'beside', turkish: 'yanında', definition: 'next to' },
    { english: 'between', turkish: 'arasında', definition: 'in the space separating two points' },
    { english: 'by', turkish: 'tarafından', definition: 'indicating the means of achieving something' },
    { english: 'during', turkish: 'esnasında', definition: 'throughout the duration of' },
    { english: 'except', turkish: 'haricinde', definition: 'not including' },
    { english: 'for', turkish: 'için', definition: 'with the object or purpose of' },
    { english: 'from', turkish: 'den', definition: 'indicating the point in space or time at which a journey, or something starts' },
    { english: 'in', turkish: 'içinde', definition: 'indicating inclusion within a space' },
    { english: 'inside', turkish: 'içinde', definition: 'with the inner part' },
    { english: 'into', turkish: 'içeri', definition: 'to the inside of' },
    { english: 'like', turkish: 'gibi', definition: 'similar to' },
    { english: 'near', turkish: 'yakınında', definition: 'at or to a short distance away' },
    { english: 'of', turkish: 'ın', definition: 'expressing the relationship between a part and a whole' },
    { english: 'on', turkish: 'üzerinde', definition: 'physically in contact with and supported by' },
    { english: 'onto', turkish: 'üzerine', definition: 'to a surface' },
    { english: 'opposite', turkish: 'karşısında', definition: 'in a position facing something' },
    { english: 'out', turkish: 'dışında', definition: 'away from the inside' },
    { english: 'over', turkish: 'üstünde', definition: 'above or higher than' },
    { english: 'since', turkish: 'den beri', definition: 'from a specific time in the past until now' },
    { english: 'through', turkish: 'aracılığıyla', definition: 'moving in one side and out of the other' },
    { english: 'throughout', turkish: 'boyunca', definition: 'in every part of' },
    { english: 'to', turkish: 'için', definition: 'expressing motion in the direction of' },
    { english: 'toward', turkish: 'doğru', definition: 'in the direction of' },
    { english: 'under', turkish: 'altında', definition: 'in a lower position' },
    { english: 'until', turkish: 'kadar', definition: 'up to the point of' },
    { english: 'up', turkish: 'yukarı', definition: 'moving to a higher position' },
    { english: 'upon', turkish: 'üzerine', definition: 'on top of' },
    { english: 'with', turkish: 'ile', definition: 'accompanied by' },
    { english: 'within', turkish: 'içinde', definition: 'inside a certain limit' },
    { english: 'without', turkish: 'olmaksızın', definition: 'in lack of' },
];

module.exports = prepositions;